"""Generate figures and LaTeX tables for the UncertaiNLP short paper.

Figures (PDF, sized for one ACL column ~3.03in):
  fig_reliability.pdf - equal-mass reliability diagram per dialect (Q1)
  fig_crc.pdf         - CRC target alpha vs realized interruption rate on the
                        two unseen channels, pooled vs per-dialect thresholds,
                        with the deferral price underneath (Q3)
Tables:
  tab_calibration.tex - ECE/Brier/Murphy/AUC by stratum + recalibration
  tab_cost.tex        - decision policies at cost ratio c=5 on held-out test
"""

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FIGS = ROOT / "figures"
TABS = ROOT / "tables"

EGY = "#2a78d6"  # categorical slot 1 (blue)
GULF = "#eb6834"  # categorical slot 2 (orange)
INK = "#1a1a19"
MUTED = "#8a897f"
GRID = "#e5e4dc"

plt.rcParams.update({
    "font.size": 8, "axes.labelsize": 8, "axes.titlesize": 8,
    "xtick.labelsize": 7, "ytick.labelsize": 7, "legend.fontsize": 7,
    "text.color": INK, "axes.edgecolor": MUTED, "axes.labelcolor": INK,
    "xtick.color": INK, "ytick.color": INK,
    "axes.grid": True, "grid.color": GRID, "grid.linewidth": 0.6,
    "axes.spines.top": False, "axes.spines.right": False,
    "pdf.fonttype": 42,
})

COL_W = 3.03  # inches, ACL column


def fig_reliability(cal):
    fig, ax = plt.subplots(figsize=(COL_W, 2.5))
    ax.plot([0, 1], [0, 1], color=MUTED, lw=1, ls=":", zorder=1)
    for name, color, marker in [("egyptian", EGY, "o"), ("gulf", GULF, "s")]:
        s = cal["strata"][name]
        conf = [b["conf"] for b in s["reliability"]]
        acc = [b["acc"] for b in s["reliability"]]
        ax.plot(conf, acc, color=color, lw=2, marker=marker, ms=4,
                label=f"{name.capitalize()}  (ECE {s['ece']:.2f})", zorder=3)
    ax.set_xlabel("Predicted $P(\\mathrm{complete})$ (bin mean)")
    ax.set_ylabel("Empirical shift rate")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.legend(loc="upper left", frameon=False)
    fig.tight_layout(pad=0.3)
    fig.savefig(FIGS / "fig_reliability.pdf")
    plt.close(fig)


def fig_crc(dec):
    alphas = sorted(float(a) for a in dec["shift"])
    fig = plt.figure(figsize=(COL_W, 3.3), constrained_layout=True)
    gs = fig.add_gridspec(2, 2, height_ratios=[2.0, 1.0])
    ax_pool = fig.add_subplot(gs[0, 0])
    ax_mond = fig.add_subplot(gs[0, 1], sharey=ax_pool)
    ax_defer = fig.add_subplot(gs[1, :])

    panels = [(ax_pool, "fc_pooled_tau", "Pooled $\\hat\\tau$"),
              (ax_mond, "fc_mondrian", "Per-dialect $\\hat\\tau$")]
    for ax, key, title in panels:
        ax.plot([0, 0.22], [0, 0.22], color=MUTED, lw=1, ls=":", zorder=1)
        for dialect, color, m in [("egyptian", EGY, "o"), ("gulf", GULF, "s")]:
            ys = [dec["shift"][f"{a:.2f}"]["per_dialect"][dialect][key]
                  for a in alphas]
            ax.plot(alphas, ys, color=color, lw=1.8, marker=m, ms=4,
                    label=dialect.capitalize(), zorder=3)
        ax.set_title(title, fontsize=8, pad=3)
        ax.set_xlim(0.03, 0.22)
        ax.set_ylim(0, 0.31)
        ax.set_xticks(alphas)
        ax.set_xticklabels(["0.05", "0.10", "0.15", "0.20"], fontsize=6.5)
    ax_pool.set_ylabel("Realized interruption rate")
    plt.setp(ax_mond.get_yticklabels(), visible=False)
    ax_pool.legend(loc="upper left", frameon=False, handlelength=1.6,
                   borderaxespad=0.2)
    ax_pool.text(0.185, 0.215, "target", color=MUTED, fontsize=6.5,
                 ha="right", va="bottom", rotation=38, rotation_mode="anchor")
    ax_mond.annotate("0.29", xy=(0.193, 0.272), ha="right", va="top",
                     color=EGY, fontsize=7)

    missed = [dec["shift"][f"{a:.2f}"]["test_missed"] for a in alphas]
    ax_defer.plot(alphas, missed, color=INK, lw=1.8, marker="D", ms=3.5,
                  zorder=3)
    ax_defer.set_ylabel("Deferred\nturn-ends")
    ax_defer.set_xlabel("Target interruption rate $\\alpha$")
    ax_defer.set_xlim(0.03, 0.22)
    ax_defer.set_ylim(0, 1)
    ax_defer.set_xticks(alphas)

    fig.savefig(FIGS / "fig_crc.pdf")
    plt.close(fig)


def tab_calibration(cal):
    rows = [
        ("All clean gold", "all"),
        ("\\quad Egyptian", "egyptian"),
        ("\\quad Gulf", "gulf"),
        ("Unseen ch.\\ (Egy.)", "test_egyptian"),
        ("Unseen ch.\\ (Gulf)", "test_gulf"),
    ]
    lines = [
        "% generated by scripts/05_figures.py -- do not edit by hand",
        "\\begin{tabular}{lrrrrr}",
        "\\toprule",
        "Stratum & $n$ & ECE & Brier & REL & RES \\\\",
        "\\midrule",
    ]
    for label, key in rows:
        s = cal["strata"][key]
        m = s["murphy"]
        lines.append(
            f"{label} & {s['n']:,} & {s['ece']:.3f} & {s['brier']:.3f}"
            f" & {m['reliability']:.3f} & {m['resolution']:.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    (TABS / "tab_calibration.tex").write_text("\n".join(lines))


def tab_cost(dec):
    c5 = dec["cost"]["c5"]
    rows = [
        ("Default $\\tau{=}0.5$", "default_0.5"),
        ("Re-threshold $\\tau{=}0.74$", "rethresh_0.74"),
        ("Bayes $\\tau{=}c/(c{+}1)$, raw $\\hat p$", "bayes_raw"),
        ("Bayes, temp.-scaled $\\hat p$", "bayes_calibrated"),
        ("CRC $\\hat\\tau(\\alpha{=}0.1)$", "crc_placeholder"),
        ("Oracle threshold (test)", "oracle_test"),
    ]
    crc = dec["shift"]["0.10"]
    lines = [
        "% generated by scripts/05_figures.py -- do not edit by hand",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Policy & Cost & Interrupt & Defer \\\\",
        "\\midrule",
    ]
    for label, key in rows:
        if key == "crc_placeholder":
            cost = 5 * (702 / 1701) * crc["test_fc"] + (999 / 1701) * crc["test_missed"]
            fc, missed = crc["test_fc"], crc["test_missed"]
        else:
            e = c5[key]
            cost, fc, missed = e["cost"], e["fc"], e["missed"]
        lines.append(f"{label} & {cost:.2f} & {fc:.3f} & {missed:.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    (TABS / "tab_cost.tex").write_text("\n".join(lines))


def main() -> None:
    FIGS.mkdir(exist_ok=True)
    TABS.mkdir(exist_ok=True)
    cal = json.load(open(DATA / "results_calibration.json"))
    dec = json.load(open(DATA / "results_decision.json"))

    # cross-check the CRC-row cost formula against the script's own numbers
    crc = dec["shift"]["0.10"]
    check = 5 * (702 / 1701) * crc["test_fc"] + (999 / 1701) * crc["test_missed"]
    n_h, n_s = dec["n"]["test_holds"], dec["n"]["test_shifts"]
    assert (n_h, n_s) == (702, 999)
    print(f"CRC(0.10) cost at c=5: {check:.3f}")

    fig_reliability(cal)
    fig_crc(dec)
    tab_calibration(cal)
    tab_cost(dec)
    print("wrote figures/fig_reliability.pdf, figures/fig_crc.pdf,")
    print("      tables/tab_calibration.tex, tables/tab_cost.tex")


if __name__ == "__main__":
    main()
